name: Build Mica

on: [ push ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - uses: gradle/wrapper-validation-action@v1

      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'zulu'

      - name: Setup git config
        run: |
          git config --global user.email "no-reply@github.com"
          git config --global user.name "Github Action"

      - name : Build with Gradle
        run: ./gradlew build --stacktrace

      - name: Upload artifacts
        uses: actions/upload-artifact@v3
        with:
          name: mica-artifacts
          path: |
            **/build/libs/mica-**.jar
            !**/build/libs/mica-**-dev-shadow.jar
            !**/build/libs/mica-**-sources.jar
